version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run:
          name: Install dependencies and run tests
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install pytest flake8
            flake8 --exclude=venv* --statistics
            pytest
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
